#!/usr/bin/env bash
# First-run wizard: ask 3 questions, seed config.sh.

wizard_maybe_run() {
    local cfg="$EMERGER_CONFIG/config.sh"
    local flag="$EMERGER_CONFIG/.wizard-done"
    [[ -f $flag ]] && return 0
    [[ ! -t 0 ]] && return 0
    (( ARG_QUIET )) && return 0

    ui_title "First-run setup"
    ui_muted "Quick 3-question setup. Skip with Ctrl-C at any time."
    mkdir -p "$EMERGER_CONFIG"

    local a1 a2 a3
    read -r -p "    Include dev toolchains (rust/npm/pip...) by default? [y/N]: " a1 || a1=n
    read -r -p "    Show weather line? [y/N]: " a2 || a2=n
    read -r -p "    Install weekly auto-update timer? [y/N]: " a3 || a3=n

    {
        printf '# eMerger user config - generated by the wizard %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf '# Edit freely; it is sourced before argument parsing.\n\n'
        [[ $a1 == [yY]* ]] && printf 'ARG_DEV=1\n'
        [[ $a2 == [yY]* ]] && printf 'ARG_WEATHER=1\n'
    } >"$cfg"

    touch "$flag"
    ui_ok "Wrote $cfg"
    if [[ $a3 == [yY]* ]]; then
        setup_cron "$EMERGER_ROOT" || true
    fi
}
